data:
  # audio config
  duration: 2
  sampling_rate: 24000
  hop_size: 256
  window_size: 1024
  extensions:
  - wav
  eps: 1e-6
  f0_predictor: rmvpe

  # content encoder config
  encoder_unit_interpolate_mode: nearest
  
  # filelist config
  flist_test: test.txt
  flist_train: train.txt
  flist_valid: val.txt

  # dwt config
  dwt_type : db10
  dwt_level : 4


# environment config
env:
  exp: vocalset_pitch
  expdir: ./logs/vibe_pitch/style_converter/pitch_ID
  port: '7002'

# singing style dict
singing_techniques:
  pitch_tech:
    straight: 0
    vibrato: 1
    Control_Group: 0
    Vibrato_Group: 1
  timbre_tech:
    straight: 0
    belt: 1
    breathy: 2
    vocal_fry: 3

# speaker dict
spk:
  VocalSet#female1: 3
  VocalSet#female2: 18
  VocalSet#female3: 15
  VocalSet#female4: 4
  VocalSet#female5: 10
  VocalSet#female6: 16
  VocalSet#female7: 12
  VocalSet#female8: 2
  VocalSet#female9: 13
  VocalSet#male1: 17
  VocalSet#male10: 9
  VocalSet#male11: 6
  VocalSet#male2: 11
  VocalSet#male3: 0
  VocalSet#male4: 5
  VocalSet#male5: 19
  VocalSet#male6: 8
  VocalSet#male7: 1
  VocalSet#male8: 7
  VocalSet#male9: 14

# trainer config
train:
  optimizer:
    betas:
    - 0.8
    - 0.99
    decay_step: 100000
    epochs: 100000
    max_training_steps : 100000
    eps: 1e-9
    gamma: 0.999875
    lr: 0.0003
    disc_lr : 0.00001
    weight_decay: 0
  d_loader:
    batch_size: 64
    num_workers: 1
  cache:
    cache_all_data: true
    cache_device: cuda
    cache_fp16: true
  logger:
    interval_force_save: 20000
    interval_log: 100
    interval_val: 50000
    save_opt: true
